### ISSUE TITLE
El sitio web debe incluir un formulario de contacto, con al menos 5 campos que incluya(un checkbox o radiobutton), un select y una imagen, con validacion realizada mediante Javascript para que los campos sean obligatorios.

### ISSUE THREAD

**Issue by AndreaLlavel** [AndreaLlavel/Comision24179-FSP-4#7]
puede consultar con el equipo

**Comment by GonzaloCristaldo** [comment]
He agregado la primera version del código. Sujeto a correciones.

**Comment by AndreaLlavel** [comment]
Hola Gonza, faltaría la validación en Javascript, como dice el enunciado de la consigna.
Así queda la tarea completa.

**Comment by GonzaloCristaldo** [comment]
Se volvió a enviar el codigo, corregido. 
Contiene las validaciones del formulario en un archivo de Js enlazado al html principal.
