### ISSUE TITLE
El sitio web debe estar estructurado utilizando etiquetas semanticas HTML correctamente. Debe pasar la validacion de validator.w3.org sin errores

### ISSUE THREAD

**Issue by AndreaLlavel** [AndreaLlavel/Comision24179-FSP-4#8]

**Comment by GonzaloCristaldo** [comment]
Revisando errores encontrados en Validator. (30)

**Comment by AndreaLlavel** [comment]
Hola Gonzalo, la validación esta representada en algún documento? que este en nuestro repositorio en git hub?

**Comment by AndreaLlavel** [comment]
Hola Gonza, subirías la muestra de los errores encontrados en el validator?.
Así ya queda completa la tarea.

**Comment by GonzaloCristaldo** [comment]
Se adjunta los pdf, con el detalle brindado por el sitio validator sobre cada uno de los html del sitio Episteme.
[Errores de becas.pdf](https://github.com/AndreaLlavel/Comision24179-FSP-4/files/15358999/Errores.de.becas.pdf)
[Errores de Contact.pdf](https://github.com/AndreaLlavel/Comision24179-FSP-4/files/15359000/Errores.de.Contact.pdf)
[Errores de cuestionario.pdf](https://github.com/AndreaLlavel/Comision24179-FSP-4/files/15359001/Errores.de.cuestionario.pdf)
[Errores de index.pdf](https://github.com/AndreaLlavel/Comision24179-FSP-4/files/15359002/Errores.de.index.pdf)
[Errores de login.pdf](https://github.com/AndreaLlavel/Comision24179-FSP-4/files/15359003/Errores.de.login.pdf)
[Errores de shop.pdf](https://github.com/AndreaLlavel/Comision24179-FSP-4/files/15359004/Errores.de.shop.pdf)

**Comment by AndreaLlavel** [comment]
Entregado y completo
